# Use official OpenJDK image with Spark preinstalled
FROM bitnami/spark:3.3.1

# Set working directory
WORKDIR /app

# Copy the JAR file into the container
COPY target/wine-predictor-1.0.jar wine-predictor.jar

# Set entrypoint to run Spark job
ENTRYPOINT ["spark-submit", "--class", "com.cs643.assignment2.App", "--master", "local[*]", "wine-predictor.jar"]
